### ISSUE TITLE
develop a PCB prototype

### ISSUE THREAD

**Issue by mohamedboubaker** [mohamedboubaker/GPS-Tracker#7]
develop a PCB that has: Voltage regulation circuit, STM32, SIM808, SIM card holder.

- [x] #4 
- [x] #8

**Comment by mohamedboubaker** [comment]
Prototype developed and manufactured. 
It appears that it has a hardware bug #2 that needs to be fixed

Below is a picture
![alt text](https://github.com/mohamedboubaker/GPS-Tracker/blob/main/Media/PCB.JPG)

**Comment by ofabric-io** [comment]
Hi! @mohamedboubaker would you mind sharing the specs to build the PCB on JLCPCB.com?
